resume: False
checkpoint_path: '/misc/lmbraid21/${lmb_username}/counterfactuals/checkpoints/${wandb.project}_${wandb.run_id}_${data.start_sample}_${data.end_sample}.tar'
record_intermediate: False
output_dir: /misc/lmbraid21/faridk/debug_multiple_classifiers

diffusion_model:
  cfg_path: "configs/stable-diffusion/v1-inference.yaml"
  ckpt_path: "/misc/lmbraid21/schrodi/pretrained_models/sd-v1-4-256.ckpt" # miniSD https://huggingface.co/justinpinkney/miniSD/tree/main

seg_model:
classifier_model:
  name: "clip"
  classifier_wrapper: True


n_samples_per_class: #2
strength: 0.382 #0.322 #0.382 #0.34 #0.3 #28 #0.25
scale: 3 #2.45 #2.85
ddim_steps: 500 #500 #375 
ddim_eta: 0.
log_rate: 1
seed: 0

data:
  _target_: data.datasets.ImageNetIndicies
  root: '/misc/scratchSSD2/datasets/ILSVRC2012/val'
  idx_to_tgt_cls_path: 'data/image_idx_to_tgt.yaml'
  image_idcs:
    - 0
    - 52
    - 53
    - 54
    - 55
    - 56
    - 57
    - 58
    - 59
    - 60
    - 62
    - 67
    - 68
    - 153
    - 200
    - 229
    - 230
    - 235
    - 238
    - 239
    - 245
    - 248
    - 251
    - 254
    - 256
    - 275
    - 281
    - 282
    - 283
    - 284
    - 285
    - 286
    - 287
    - 288
    - 289
    - 291
    - 293
    - 340
    - 344
    - 358
    - 361
    - 383
    - 387
    - 396
    - 1000
    - 1052
    - 1053
    - 1054
    - 1055
    - 1056
    - 1057
    - 1058
    - 1059
    - 1060
    - 1062
    - 1067
    - 1068
    - 1153
    - 1200
    - 1229
    - 1230
    - 1235
    - 1238
    - 1239
    - 1245
    - 1248
    - 1251
    - 1254
    - 1256
    - 1275
    - 1281
    - 1282
    - 1283
    - 1284
    - 1285
    - 1286
    - 1287
    - 1288
    - 1289
    - 1291
    - 1293
    - 1340
    - 1344
    - 1358
    - 1361
    - 1383
    - 1387
    - 1396
    - 2000
    - 2052
    - 2053
    - 2054
    - 2055
    - 2056
    - 2057
    - 2058
    - 2059
    - 2060
    - 2062
    - 2067
    - 2068
    - 2153
    - 2200
    - 2229
    - 2230
    - 2235
    - 2238
    - 2239
    - 2245
    - 2248
    - 2251
    - 2254
    - 2256
    - 2275
    - 2281
    - 2282
    - 2283
    - 2284
    - 2285
    - 2286
    - 2287
    - 2288
    - 2289
    - 2291
    - 2293
    - 2340
    - 2344
    - 2358
    - 2361
    - 2383
    - 2387
    - 2396
    - 3000
    - 3052
    - 3053
    - 3054
    - 3055
    - 3056
    - 3057
    - 3058
    - 3059
    - 3060
    - 3062
    - 3067
    - 3068
    - 3153
    - 3200
    - 3229
    - 3230
    - 3235
    - 3238
    - 3239
    - 3245
    - 3248
    - 3251
    - 3254
    - 3256
    - 3275
    - 3281
    - 3282
    - 3283
    - 3284
    - 3285
    - 3286
    - 3287
    - 3288
    - 3289
    - 3291
    - 3293
    - 3340
    - 3344
    - 3358
    - 3361
    - 3383
    - 3387
    - 3396
    - 4000
    - 4052
    - 4053
    - 4054
    - 4055
    - 4056
    - 4057
    - 4058
    - 4059
    - 4060
    - 4062
    - 4067
    - 4068
    - 4153
    - 4200
    - 4229
    - 4230
    - 4235
    - 4238
    - 4239
    - 4245
    - 4248
    - 4251
    - 4254
    - 4256
    - 4275
    - 4281
    - 4282
    - 4283
    - 4284
    - 4285
    - 4286
    - 4287
    - 4288
    - 4289
    - 4291
    - 4293
    - 4340
    - 4344
    - 4358
    - 4361
    - 4383
    - 4387
    - 4396
    - 5000
    - 5052
    - 5053
    - 5054
    - 5055
    - 5056
    - 5057
    - 5058
    - 5059
    - 5060
    - 5062
    - 5067
    - 5068
    - 5153
    - 5200
    - 5229
    - 5230
    - 5235
    - 5238
    - 5239
    - 5245
    - 5248
    - 5251
    - 5254
    - 5256
    - 5275
    - 5281
    - 5282
    - 5283
    - 5284
    - 5285
    - 5286
    - 5287
    - 5288
    - 5289
    - 5291
    - 5293
    - 5340
    - 5344
    - 5358
    - 5361
    - 5383
    - 5387
    - 5396

  split: 'val'
  return_tgt_cls: True
  batch_size: 1
  start_sample: 0
  end_sample: 50

sampler:
  self_recurrence: 0
  self_recurrence_every_n_steps: 0
  enforce_same_norms: True
  guidance: "projected"
  cone_projection_type: "zero_binning"
  classifier_lambda: 3.95 #3.3
  dist_lambda: 1.2
  masked_guidance: False
  backprop_diffusion: True   
  lp_custom: 1
  deg_cone_projection: 50.


lmb_username: 'faridk'

wandb:
  entity: 'kifarid'
  enabled: False
  project: 'cdiff'
  checkpoint_path: '/misc/lmbraid21/${lmb_username}/counterfactuals/checkpoints/${wandb.project}_${wandb.run_id}_${data.start_sample}_${data.end_sample}.tar'
  run_id: debug
