resume: False
checkpoint_path: '/misc/lmbraid21/${lmb_username}/counterfactuals/checkpoints/${wandb.project}_${wandb.run_id}_${data.start_sample}_${data.end_sample}.tar'
record_intermediate: False
output_dir: /misc/lmbraid21/faridk/evolution
mode: reversibility

diffusion_model:
  cfg_path: "configs/stable-diffusion/v1-inference.yaml"
  ckpt_path: "/misc/lmbraid21/schrodi/pretrained_models/sd-v1-4-256.ckpt" # miniSD https://huggingface.co/justinpinkney/miniSD/tree/main

seg_model:
classifier_model:
  name: "resnet50"


n_samples_per_class: #2
strength: 0.382 #0.322 #0.382 #0.34 #0.3 #28 #0.25
scale: 3 #2.45 #2.85
ddim_steps: 500 #500 #375 
ddim_eta: 0.
log_rate: 1
seed: 0

data:
  _target_: data.datasets.ImageNetIndicies
  root: '/misc/scratchSSD2/datasets/ILSVRC2012/val'
  idx_to_tgt_cls_path: 'data/image_idx_to_tgt.yaml'
  image_idcs:
    - 10289
    - 48456
    - 7563
    - 19534
    - 3324
    - 32487
    - 36918
    - 19679
    - 39585
    - 18789
    - 6571
    - 49839
    - 8460
    - 33185
    - 14235
    - 26004
    - 361
    - 3714
    - 6478
    - 18062
    - 33920
    - 23417
    - 6982
    - 10870
    - 34425
    - 23480
    - 14803
    - 10423
    - 4257
    - 38090
    - 36990
    - 38418
    - 31724
    - 48298
    - 31640
    - 33251
    - 14568
    - 24023
    - 15001
    - 44824
    - 25519
    - 33936
    - 32820
    - 47653
    - 46975
    - 33169
    - 38777
    - 10675
    - 18717
    - 47124
    - 24110
    - 28521
    - 15944
    - 7425
    - 33488
    - 20999
    - 2703
    - 36059
    - 18568
    - 17438
    - 42655
    - 13924
    - 41710
    - 26645
    - 22422
    - 21856
    - 33718
    - 4620
    - 4079
    - 35841
    - 8423
    - 12319
    - 17405
    - 35210
    - 49277
    - 24523
    - 41803
    - 28222
    - 23361
    - 16874
    - 24797
    - 32617
    - 36192
    - 47489
    - 12443
    - 14962
    - 26267
    - 24114
    - 48488
    - 1467
    - 23797
    - 41796
    - 1089
    - 39240
    - 7464
    - 11888
    - 25906
    - 4466
    - 2859
    - 45129

  split: 'val'
  return_tgt_cls: True
  batch_size: 1
  start_sample: 0
  end_sample: 50

sampler:
  self_recurrence: 0
  self_recurrence_every_n_steps: 0
  enforce_same_norms: True
  guidance: "projected"
  cone_projection_type: "zero_binning"
  classifier_lambda: 3.95 #3.3
  dist_lambda: 1.2
  masked_guidance: False
  backprop_diffusion: True   
  lp_custom: 1
  deg_cone_projection: 50.


lmb_username: 'schrodi'

wandb:
  entity: 'kifarid'
  enabled: False
  project: 'cdiff'
  checkpoint_path: '/misc/lmbraid21/${lmb_username}/counterfactuals/checkpoints/${wandb.project}_${wandb.run_id}_${data.start_sample}_${data.end_sample}.tar'
  run_id: debug