resume: False
checkpoint_path: '/misc/lmbraid21/${lmb_username}/counterfactuals/checkpoints/${wandb.project}_${wandb.run_id}_${data.start_sample}_${data.end_sample}.tar'
record_intermediate: False
output_dir: /misc/lmbraid21/faridk/spurious_correlations/fireboat_lifeboat
mode: generate_user_defined

diffusion_model:
  cfg_path: "configs/stable-diffusion/v1-inference.yaml"
  ckpt_path: "/misc/lmbraid21/schrodi/pretrained_models/sd-v1-4-256.ckpt" # miniSD https://huggingface.co/justinpinkney/miniSD/tree/main

seg_model:
classifier_model:
  name: "resnet50"
  classifier_wrapper: True


n_samples_per_class: #2
strength: 0.382 #0.322 #0.382 #0.34 #0.3 #28 #0.25
scale: 3 #2.45 #2.85
ddim_steps: 500 #500 #375 
ddim_eta: 0.
log_rate: 1
seed: 0

data:
  _target_: data.datasets.ImageNetIndicies
  root: '/misc/scratchSSD2/datasets/ILSVRC2012/val'
  idx_to_tgt_cls_path: 'data/image_idx_to_tgt.yaml'
  image_idcs:
    - 554
    - 1554
    - 2554
    - 3554
    - 4554
    - 5554
    - 6554
    - 7554
    - 8554
    - 9554
    - 10554
    - 11554
    - 12554
    - 13554
    - 14554
    - 15554
    - 16554
    - 17554
    - 18554
    - 19554
    - 20554
    - 21554
    - 22554
    - 23554
    - 24554
    - 25554
    - 26554
    - 27554
    - 28554
    - 29554
    - 30554
    - 31554
    - 32554
    - 33554
    - 34554
    - 35554
    - 36554
    - 37554
    - 38554
    - 39554
    - 40554
    - 41554
    - 42554
    - 43554
    - 44554
    - 45554
    - 46554
    - 47554
    - 48554
    - 49554
    - 0625
    - 1625
    - 2625
    - 3625
    - 4625
    - 5625
    - 6625
    - 7625
    - 8625
    - 9625
    - 10625
    - 11625
    - 12625
    - 13625
    - 14625
    - 15625
    - 16625
    - 17625
    - 18625
    - 19625
    - 20625
    - 21625
    - 22625
    - 23625
    - 24625
    - 25625
    - 26625
    - 27625
    - 28625
    - 29625
    - 30625
    - 31625
    - 32625
    - 33625
    - 34625
    - 35625
    - 36625
    - 37625
    - 38625
    - 39625
    - 40625
    - 41625
    - 42625
    - 43625
    - 44625
    - 45625
    - 46625
    - 47625
    - 48625
    - 49625

  split: 'val'
  return_tgt_cls: True
  batch_size: 4
  start_sample: 0
  end_sample: 50

target_classes:
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 625
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554
    - 554

sampler:
  self_recurrence: 0
  self_recurrence_every_n_steps: 0
  enforce_same_norms: True
  guidance: "projected"
  cone_projection_type: "zero_binning"
  classifier_lambda: 3.95 #3.3
  dist_lambda: 1.2
  masked_guidance: False
  backprop_diffusion: True   
  lp_custom: 1
  deg_cone_projection: 50.


lmb_username: 'schrodi'

wandb:
  entity: 'kifarid'
  enabled: False
  project: 'cdiff'
  checkpoint_path: '/misc/lmbraid21/${lmb_username}/counterfactuals/checkpoints/${wandb.project}_${wandb.run_id}_${data.start_sample}_${data.end_sample}.tar'
  run_id: debug