data_path: '/misc/scratchSSD2/datasets/ILSVRC2012/val'

diffusion_model:
  cfg_path: "configs/latent-diffusion/cin256-v2.yaml"
  ckpt_path: "models/ldm/cin256-v2/model.ckpt"

seg_model:


classifier_model:
  name: "efficientnet_b0"

n_samples_per_class: 2
strength: 0.27
scale: 3.0
ddim_steps: 500
ddim_eta: 0.

sampler:

  enforce_same_norms: True
  guidance: "projected"
  classifier_lambda: 1.8
  dist_lambda: 0.3
  masked_guidance: False
  backprop_diffusion: False
  lp_custom: 1
