diffusion_model:
  cfg_path: "configs/latent-diffusion/cin256-v2.yaml"
  ckpt_path: "models/ldm/cin256-v2/model.ckpt"

seg_model:
classifier_model:
  name: "efficientnet_b0"


n_samples_per_class: #2
strength: 0.36 #0.3 #28 #0.25
scale: 2.85
ddim_steps: 375 
ddim_eta: 0.
log_rate: 10

data:
  _target_: scripts.dvce.ImageNet
  root: '/misc/scratchSSD2/datasets/ILSVRC2012/val'
  idx_to_tgt_cls_path: 'data/image_idx_to_tgt_class_closest_5.yaml'
  split: 'val'
  return_tgt_cls: True
  batch_size: 2


 

sampler:
  enforce_same_norms: True
  guidance: "non-projection"
  classifier_lambda: 1.8
  dist_lambda: 0.3
  masked_guidance: False
  backprop_diffusion: True   
  lp_custom: 1
  deg_cone_projection: 30.

wandb:
  enabled: True