resume: False
fixed_seed: False
record_intermediate: False
output_dir: '/misc/lmbraid21/faridk/debug_s_celeb_new'

diffusion_model:
  cfg_path: "configs/latent-diffusion/celebahq-ldm-vq-4.yaml" #"configs/stable-diffusion/v1-inference.yaml"
  ckpt_path: "models/ldm/celeba256/model.ckpt" # miniSD https://huggingface.co/justinpinkney/miniSD/tree/main
classifier_model:
  classifier_path: "/misc/lmbraid21/schrodi/pretrained_models/celeba_hq_decision_densenet/celebamaskhq/checkpoint.tar"
  classifier_wrapper: True

n_samples_per_class: #2
strength: 0.4 #0.322 #0.382 #0.34 #0.3 #28 #0.25
scale: 3 #2.45 #2.85
ddim_steps: 500 #500 #375 
ddim_eta: 0.
log_rate: 1

data:
  _target_: data.datasets.CelebAHQDataset #Select
  data_dir: '/misc/lmbraid21/schrodi/CelebAMask-HQ'
  random_crop: False
  random_flip: False
  partition: 'test'
  query_label: 31 # 31 -> smiling; 39 -> age
  normalize: False
  batch_size: 1
  shard: 0
  image_idcs: 
    - 5
    - 5
    - 2
    - 2
  num_shards: 7

sampler:
  self_recurrence: 0
  self_recurrence_every_n_steps: 0
  enforce_same_norms: True
  guidance: "projected" #"projected"
  cone_projection_type: "zero_binning"
  classifier_lambda: 4 #1. #3.3
  dist_lambda: 3.3
  masked_guidance: False
  backprop_diffusion: True   
  lp_custom: 1
  deg_cone_projection: 35.

lmb_username: 'faridk'
